version: "2" 
services:
  php:
    build: 
      context: .
    image: myimage    
    ports:
      - "30001:80"
    container_name: moe-php-app
  mysql:
    image: 65.2.70.57:8083/repository/php_mysql_app/mysql:6
    networks:
      - backend
    container_name: moe-mysql-app      
  phpmyadmin:
    image: 65.2.70.57:8083/repository/php_mysql_app/phpmyadmin/phpmyadmin:6
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "30002:80"  
    container_name: moe-phpmyadmin-app
networks:
  frontend:
  backend:
